// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions  get web => FirebaseOptions(
    apiKey: const String.fromEnvironment('API_KEY_FIREBASE_WEB'),
    appId: '1:152357187715:web:284ee39879368f6ea7ebb6',
    messagingSenderId: '152357187715',
    projectId: 'iocl-quiz-host',
    authDomain: 'iocl-quiz-host.firebaseapp.com',
    databaseURL: 'https://iocl-quiz-host-default-rtdb.firebaseio.com',
    storageBucket: 'iocl-quiz-host.firebasestorage.app',
    measurementId: 'G-MPBLVN10FC',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['API_KEY_FIREBASE_ANDROID']!,
    appId: '1:152357187715:android:f42d3144b35079b2a7ebb6',
    messagingSenderId: '152357187715',
    projectId: 'iocl-quiz-host',
    databaseURL: 'https://iocl-quiz-host-default-rtdb.firebaseio.com',
    storageBucket: 'iocl-quiz-host.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['API_KEY_FIREBASE_IOS']!,
    appId: '1:152357187715:ios:0b97e971fba4424fa7ebb6',
    messagingSenderId: '152357187715',
    projectId: 'iocl-quiz-host',
    databaseURL: 'https://iocl-quiz-host-default-rtdb.firebaseio.com',
    storageBucket: 'iocl-quiz-host.firebasestorage.app',
    iosBundleId: 'com.example.quizHost',
  );

}